
spring:
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: "*"
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    bootstrap-servers:
      - PLAINTEXT://broker-1:19092
      - PLAINTEXT://broker-2:19092
      - PLAINTEXT://broker-3:19092
  datasource:
    username: ${DB_USERNAME:vtbet}
    password: ${DB_PASSWORD:vtbet}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/vtbet}
server:
  port: 8597
  error:
    include-message: always
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
