spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers:
      - PLAINTEXT://broker-1:19092
      - PLAINTEXT://broker-2:19092
      - PLAINTEXT://broker-3:19092
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          sports-client:
            url: ${SPORTS_URL:http://localhost:8081}
          user-accounter-client:
            url: ${USER_ACCOUNTER_URL}
  application:
    name: "bets-handler"
  transaction:
    default-timeout: 5s
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true

  datasource:
    username: ${DB_USERNAME:vtbet}
    password: ${DB_PASSWORD:vtbet}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/vtbet}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
vtbet:
  ratio-decrease-value: 0.01

resilience4j.circuitbreaker:
  configs:
    default:
      ignoreExceptions:

server:
  port: 8492
  error:
    include-message: always
