spring:
  application:
    name: "main"
  transaction:
    default-timeout: 5s
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true

server:
  port: 8080
  error:
    include-message: always

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}

vtbet:
  gateway:
    service-auth: ${AUTH_URL:http://auth:8440/}
    service-bets-handler: ${BETS_HANDLER_URL:http://bets-handler:8492/}
    service-sports: ${SPORTS_URL:http://sports:8081/}
    service-user-accounter: ${USER_ACCOUNTER_URL:http://user-accounter:8601/}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - url: ${BETS_HANDLER_SWAGGER_URL}
        name: bets handler service
      - url: ${SPORTS_SWAGGER_URL}
        name: sport service
      - url: ${USER_ACCOUNTER_SWAGGER_URl}
        name: user accounter service
      - url: ${AUTH_SWAGGER_URL}
        name: auth service

auth:
  keys:
    public-key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAypqDZKKWllCE7xtTtJD/
      5gy/Cpk/uVsACJzV88IVCU98kykx7kjotYLPw8GcQ5sspp7iOa04AhPkbgCJyhpg
      3UdTsn+z/k3CpEUyyBVf51Fthjosbj0lvqx3PYLNm5FveZysVtze1SSOXCu4RaNV
      Idrh/4QP+YbOLmARWBx29RHQxXavlvcb91/eYW/IK3U5lC4LuFvF5+CUWDIOsGVs
      D3ebJY67bIrClg2/9QDCxOI7TLQZwjNZ1bppTNl19zX0oJWh+5xFNb6AJhiPOJMS
      U8504NENkG7FG37jKOW0+kPhN/35iLxmcjdBoJHS88wWtmw4g8Jqyw+Zrw8wf5Ac
      8wIDAQAB
      -----END PUBLIC KEY-----
