spring:
  application:
    name: "s3"
  transaction:
    default-timeout: 5s

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:vtbets}
  secretKey: ${MINIO_SECRET_KEY:vtbetsvtbets}
  bucket: ${MINIO_BUCKET:passports}

server:
  port: 8090
  error:
    include-message: always

websocket:
  s3-topic: topic
  s3-app: app