spring:
  application:
    name: "user-accounter"
  transaction:
    default-timeout: 5s
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true

  r2dbc:
    username: ${DB_USERNAME:vtbet}
    password: ${DB_PASSWORD:vtbet}
    url: ${DB_URL:r2dbc:postgresql://localhost:5432/vtbet}
vtbet:
  ratio-decrease-value: 0.01

server:
  port: 8601
  error:
    include-message: always

websocket:
  s3-address: ws://localhost:8090/ws
  s3-topic: topic
  s3-app: app

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
