spring:
  application:
    name: gateway-server
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8090}/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - url: /bets-handler-service/v3/api-docs
        name: Bets handler service
      - url: /sport-service/v3/api-docs
        name: sport Service
      - url: /user-accounter-service/v3/api-docs
        name: user accaounter service