spring:
  application:
    name: configs
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:/config/
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}

server:
  port: 8489
