version: '3.9'

services:
  postgresql:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_DB: vtbet
      POSTGRES_USER: vtbet
      POSTGRES_PASSWORD: vtbet
      PGDATA: /var/lib/postgresql/vtbet/data
    volumes:
      - postgres:/var/lib/pgsql/data
    networks:
      - backend
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "vtbet" ]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      postgresql:
        condition: service_healthy
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/vtbet
      - --username=vtbet
      - --password=vtbet
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  eureka:
    build: ./vtbet-eureka
    ports:
      - "8761:8761"
    networks:
      - backend
    depends_on:
      - postgresql
      - liquibase-migrations

  configs:
    build: ./vtbet-configs
    ports:
      - "8489:8489"
    networks:
      - backend
    depends_on:
      - postgresql
      - liquibase-migrations
      - eureka
    environment:
      EUREKA_URL: http://eureka:8761/eureka

  user-accounter:
    build: ./vtbet-user-accounter
    ports:
      - "8601:8601"
    networks:
      - backend
    depends_on:
      - postgresql
      - liquibase-migrations
      - configs
    environment:
      EUREKA_URL: http://eureka:8761/eureka
      CONFIG_URL: http://configs:8489/
      DB_USERNAME: vtbet
      DB_PASSWORD: vtbet
      DB_URL: r2dbc:postgresql://postgresql:5432/vtbet

  sports:
    build: ./vtbet-sports
    ports:
      - "8081:8081"
    networks:
      - backend
    depends_on:
      - postgresql
      - liquibase-migrations
      - configs
    environment:
      EUREKA_URL: http://eureka:8761/eureka
      CONFIG_URL: http://configs:8489/
      DB_USERNAME: vtbet
      DB_PASSWORD: vtbet
      DB_URL: jdbc:postgresql://postgresql:5432/vtbet

  bets-handler:
    build: ./vbet-bets-handler
    ports:
      - "8492:8492"
    networks:
      - backend
    depends_on:
      - postgresql
      - liquibase-migrations
      - configs
    environment:
      EUREKA_URL: http://eureka:8761/eureka
      SPORTS_URL: http://sports:8081/
      USER_ACCOUNTER_URL: http://user-accounter:8601/
      CONFIG_URL: http://configs:8489/
      DB_USERNAME: vtbet
      DB_PASSWORD: vtbet
      DB_URL: jdbc:postgresql://postgresql:5432/vtbet

  main:
    build: ./vtbet-main
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - postgresql
      - liquibase-migrations
      - configs
    environment:
      EUREKA_URL: http://eureka:8761/eureka
      CONFIG_URL: http://configs:8489/
      AUTH_URL: http://auth:8440/
      BETS_HANDLER_URL: http://bets-handler:8492/
      SPORTS_URL: http://sports:8081/
      USER_ACCOUNTER_URL: http://user-accounter:8601/

  auth:
    build: ./vtbet-auth
    ports:
      - "8440:8440"
    networks:
      - backend
    depends_on:
      - postgresql
      - liquibase-migrations
      - configs
    environment:
      EUREKA_URL: http://eureka:8761/eureka
      CONFIG_URL: http://configs:8489/
      DB_USERNAME: vtbet
      DB_PASSWORD: vtbet
      DB_URL: jdbc:postgresql://postgresql:5432/vtbet

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: vtbets
      MINIO_ROOT_PASSWORD: vtbetsvtbets
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres:
  pgadmin:
  minio-storage:

networks:
  backend: