version: '3.9'

services:
  postgresql:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_DB: vtbet
      POSTGRES_USER: vtbet
      POSTGRES_PASSWORD: vtbet
      PGDATA: /var/lib/postgresql/vtbet/data
    volumes:
      - postgres:/var/lib/pgsql/data
    networks:
      - backend
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "vtbet" ]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      postgresql:
        condition: service_healthy
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/vtbet
      - --username=vtbet
      - --password=vtbet
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  application:
    build: .
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - postgresql
      - liquibase-migrations
    environment:
      DB_USERNAME: vtbet
      DB_PASSWORD: vtbet
      DB_URL: jdbc:postgresql://postgresql:5432/vtbet

volumes:
  postgres:
  pgadmin:

networks:
  backend: