version: '3.9'

services:
  postgresql:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_DB: vtbet
      POSTGRES_USER: vtbet
      POSTGRES_PASSWORD: vtbet
      PGDATA: /var/lib/postgresql/vtbet/data
    volumes:
      - postgres:/var/lib/pgsql/data
    networks:
      - backend
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "vtbet" ]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      postgresql:
        condition: service_healthy
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/vtbet
      - --username=vtbet
      - --password=vtbet
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend
#
#  eureka:
#    build: ./vtbet-eureka
#    ports:
#      - "8761:8761"
#    networks:
#      - backend
#    depends_on:
#      - postgresql
#      - liquibase-migrations
#
#  configs:
#    build: ./vtbet-configs
#    ports:
#      - "8489:8489"
#    networks:
#      - backend
#    depends_on:
#      - postgresql
#      - liquibase-migrations
#      - eureka
#
#  user-accounter:
#    build: ./vtbet-user-accounter
#    ports:
#      - "8601:8601"
#    networks:
#      - backend
#    depends_on:
#      - postgresql
#      - liquibase-migrations
#      - configs
#    environment:
#      DB_USERNAME: vtbet
#      DB_PASSWORD: vtbet
#      DB_URL: jdbc:postgresql://postgresql:5432/vtbet
#
#  sports:
#    build: ./vtbet-sports
#    ports:
#      - "8081:8081"
#    networks:
#      - backend
#    depends_on:
#      - postgresql
#      - liquibase-migrations
#      - configs
#    environment:
#      DB_USERNAME: vtbet
#      DB_PASSWORD: vtbet
#      DB_URL: jdbc:postgresql://postgresql:5432/vtbet
#
#  bets-handler:
#    build: ./vtbet-sports
#    ports:
#      - "8492:8492"
#    networks:
#      - backend
#    depends_on:
#      - postgresql
#      - liquibase-migrations
#      - configs
#    environment:
#      DB_USERNAME: vtbet
#      DB_PASSWORD: vtbet
#      DB_URL: jdbc:postgresql://postgresql:5432/vtbet

volumes:
  postgres:
  pgadmin:

networks:
  backend: