on:
  push:
    paths:
      - vtbet-common/**
      - vbet-bets-handler/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}

      - name: Build docker image
        run: docker build -t ghcr.io/${{ secrets.USERNAME }}/vbet-bets-handler:latest . -f vbet-bets-handler/Dockerfile

      - name: Push docker image
        run: docker push ghcr.io/${{ secrets.TOKEN }}/vbet-bets-handler:latest