/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.itmo.vtbet

import org.junit.jupiter.api.Test
import org.springframework.boot.test.context.SpringBootTest

@SpringBootTest
class VtbetApplicationTests {

    @Test
    fun contextLoads() {
    }

}
