spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true

  datasource:
      username: root
      password: root
      url: jdbc:postgresql://localhost:5432/vtbet

server:
  error:
    include-message: always
