spring:
  transaction:
    default-timeout: 5s
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true

  datasource:
    username: vtbet
    password: vtbet
    url: jdbc:postgresql://localhost:5432/vtbet

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect

jakarta:
  persistence:
    jdbc:
      url: jdbc:postgresql://localhost:5432/vtbet

server:
  port: 8080
  error:
    include-message: always

vtbet:
  ratio-decrease-value: 0.01
