on:
  push:
    branches:
      - main
    paths:
      - vtbet-common/**
      - vtbet-sports/**

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ruskaof
          password: ${{ secrets.TOKEN }}

      - name: Build docker image
        run: docker build -t ghcr.io/ruskaof/vtbet-sports:latest vtbet-sports -f vtbet-sports/Dockerfile

      - name: Push docker image
        run: docker push ghcr.io/ruskaof/vtbet-sports:latest
